OPCUABuilder uses max_package_size from broker.json
OI4/oi4-oec-service pull request #117
Opened 2022-08-02 10:00 UTC by chrfranz

Removed access to environment variable `OI4_EDGE_MQTT_MAX_MESSAGE_SIZE` from `OPCUABuilder`. Introduced a new constructor-argument for the maximum message size. Updated  `OI4ApplicationBuilder ` and `OI4ApplicationFactory` so that the maximum message size is now used when creating the `OPCUABuilder`.

2022-08-03 08:08 UTC, Weinschenk requested changes

2022-08-03 08:08 UTC, Weinschenk commented on packages/oi4-oec-service-node/src/application/OI4ApplicationFactory.ts
> +        const opcUaBuilder = new OPCUABuilder(this.resources.oi4Id, this.serviceType, maximumPacketSize);
The instantiation with new will cause a tight coupling and makes it impossible to use dependency injection (inversion of control)
```suggestion
if(this.opcUaBuilder === undefined){
       this.opcUaBuilder = new OPCUABuilder(this.resources.oi4Id, this.serviceType, maximumPacketSize);
}
```

2022-08-03 11:51 UTC, chrfranz commented on packages/oi4-oec-service-node/src/application/OI4ApplicationFactory.ts
> +        const opcUaBuilder = new OPCUABuilder(this.resources.oi4Id, this.serviceType, maximumPacketSize);
Updated source code according the proposed change.

2022-08-09 04:30 UTC, Weinschenk approved these changes

2022-08-09 04:30 UTC, merged