OI4-208-4
OI4/oi4-oec-service pull request #34
Opened 2022-05-31 12:38 UTC by vdedominicis-EH

@Weinschenk  Here we are :)

2022-05-31 13:13 UTC, Weinschenk requested changes

2022-05-31 13:13 UTC, Weinschenk commented on packages/oi4-oec-service-node/src/Proxy/Messagebus/index.ts
>              //if (process.env.USE_UNSECURE_BROKER as string !== 'true') { // This should be the normal case, we connect securely
Please remove obsolete code

2022-05-31 13:13 UTC, Weinschenk commented on packages/oi4-oec-service-node/src/Utilities/Helpers/Types.ts
> +export type ValidatedCredentials = {
I think we do not need this type if we directly throw the error

2022-05-31 13:13 UTC, Weinschenk commented on packages/oi4-oec-service-node/src/Utilities/Helpers/MqttSettingsHelper.ts
> +    getUserCredentials(): Credentials {
maybe rename the function to loadUserCredentials to make clear that the credentials are loaded from file and not only retrieved from a local variable

2022-05-31 13:13 UTC, Weinschenk commented on packages/oi4-oec-service-node/src/Utilities/Helpers/MqttSettingsHelper.ts
> +    areEncodedCredentialsInvalid(encodedCredentials: string): ValidatedCredentials {
It is better to avoid the negative (meaning check for valid in this case). What about checkCredentials?

2022-05-31 13:15 UTC, Weinschenk commented on packages/oi4-oec-service-node/src/Utilities/Helpers/MqttSettingsHelper.ts
> +        if (fs.existsSync(this.fileLocation)) {
```suggestion
        if (!fs.existsSync(this.fileLocation)) {
          throw new Error('Credentials file not found');
        }
```

2022-05-31 13:15 UTC, Weinschenk commented on packages/oi4-oec-service-node/src/Utilities/Helpers/MqttSettingsHelper.ts
> +        if (fs.existsSync(this.fileLocation)) {
To get rid of the else block

2022-05-31 13:15 UTC, vdedominicis-EH commented on packages/oi4-oec-service-node/src/Proxy/Messagebus/index.ts
>              //if (process.env.USE_UNSECURE_BROKER as string !== 'true') { // This should be the normal case, we connect securely
Done.

2022-05-31 13:32 UTC, vdedominicis-EH commented on packages/oi4-oec-service-node/src/Utilities/Helpers/Types.ts
> +export type ValidatedCredentials = {
Done

2022-05-31 13:32 UTC, vdedominicis-EH commented on packages/oi4-oec-service-node/src/Utilities/Helpers/MqttSettingsHelper.ts
> +    getUserCredentials(): Credentials {
Done.

2022-05-31 13:33 UTC, vdedominicis-EH commented on packages/oi4-oec-service-node/src/Utilities/Helpers/MqttSettingsHelper.ts
> +    areEncodedCredentialsInvalid(encodedCredentials: string): ValidatedCredentials {
Also done.

2022-05-31 13:38 UTC, vdedominicis-EH commented on packages/oi4-oec-service-node/src/Utilities/Helpers/MqttSettingsHelper.ts
> +        if (fs.existsSync(this.fileLocation)) {
Done

2022-05-31 14:26 UTC, vdedominicis-EH commented
@Weinschenk All change request satisfied, ready to be re-reviewed :)

2022-06-01 06:39 UTC, Weinschenk requested changes

2022-06-01 06:39 UTC, Weinschenk commented on packages/oi4-oec-service-node/src/Utilities/Helpers/MqttSettingsHelper.ts
> +        const decodedCredentials = atob(encodedCredentials);
atob is for web applications only (part of the window object). It is not part of node (when running as a non-web app). Please change to node's Buffer implementation

2022-06-01 06:39 UTC, Weinschenk commented on packages/oi4-oec-service-node/src/Utilities/Helpers/MqttSettingsHelper.ts
> +        if(btoa(decodedCredentials) !== encodedCredentials) {
btoa is for web applications only (part of the window object). It is not part of node (when running as a non-web app). Please change to node's Buffer implementation

2022-06-01 06:39 UTC, Weinschenk commented on packages/oi4-oec-service-node/src/Utilities/Helpers/MqttSettingsHelper.ts
> +            decodedCredentials.split(':').length != 2) {
No need to check if there is more than one : . The password may contain a : and that is fine.
If we want to add another check, we could test, that the username only consist of [rfc3986](https://datatracker.ietf.org/doc/html/rfc3986) characters. Meaning: (a-zA-Z), numbers (0-9), -_.~

2022-06-01 09:38 UTC, vdedominicis-EH commented on packages/oi4-oec-service-node/src/Utilities/Helpers/MqttSettingsHelper.ts
> +        if(btoa(decodedCredentials) !== encodedCredentials) {
Done.

2022-06-01 09:38 UTC, vdedominicis-EH commented on packages/oi4-oec-service-node/src/Utilities/Helpers/MqttSettingsHelper.ts
> +        const decodedCredentials = atob(encodedCredentials);
DOne.

2022-06-01 10:26 UTC, vdedominicis-EH commented on packages/oi4-oec-service-node/src/Utilities/Helpers/MqttSettingsHelper.ts
> +            decodedCredentials.split(':').length != 2) {
Partially done, discussed in person

2022-06-01 12:33 UTC, Weinschenk approved these changes

2022-06-01 12:33 UTC, merged