OI4-198
OI4/oi4-oec-service pull request #36
Opened 2022-05-31 13:18 UTC by RiccardoScuderi-EH

2022-06-01 11:36 UTC, vdedominicis-EH submitted a review, later dismissed
Looks good to me, but mybe @Weinschenk wants to review it as well.

2022-06-01 11:36 UTC, vdedominicis-EH commented on packages/oi4-oec-service-node/jest.config.js
> +// eslint-disable-next-line @typescript-eslint/no-var-requires
I have no problem with the following instruction, maybe we can remove this disable next line

2022-06-01 11:36 UTC, vdedominicis-EH commented on packages/oi4-oec-service-node/src/Proxy/Messagebus/MqttSettings.ts
> -export interface MqttSettings {
This change is also in the other PR, as discussed double check the changes and the branches.

2022-06-01 11:46 UTC, RiccardoScuderi-EH commented on packages/oi4-oec-service-node/jest.config.js
> +// eslint-disable-next-line @typescript-eslint/no-var-requires
removed and it workd
s

2022-06-01 12:54 UTC, Weinschenk requested changes

2022-06-01 12:54 UTC, Weinschenk commented on packages/oi4-oec-service-node/src/Proxy/Messagebus/MqttSettings.ts
> +    useUnsecureBroker?: boolean;
Please remove the possibility to use an unsecured broker connection

2022-06-01 12:54 UTC, Weinschenk commented on packages/oi4-oec-service-node/tests/connect_via_mqtts.test.ts
> +import mqtt = require('async-mqtt');
Please move tests to src/__tests__ and fixtures to src/__fixtures__

2022-06-01 12:54 UTC, Weinschenk commented on packages/oi4-oec-service-node/tests/fixtures/README
> +DIE Zertifikate SIND 1 JAHR GÜLTIG.
Please move to src/__fixtures__

2022-06-01 12:54 UTC, Weinschenk commented on packages/oi4-oec-service-node/tests/fixtures/ca-root-cert.crt
> +-----BEGIN CERTIFICATE-----
Please move to src/__fixtures__

2022-06-01 12:54 UTC, Weinschenk commented on packages/oi4-oec-service-node/tests/fixtures/decrypted-client-cert.crt
> +-----BEGIN CERTIFICATE-----
Please move to src/__fixtures__

2022-06-01 12:54 UTC, Weinschenk commented on packages/oi4-oec-service-node/tests/fixtures/decrypted-client-key.key
> +-----BEGIN PRIVATE KEY-----
Please move to src/__fixtures__

2022-06-01 12:54 UTC, Weinschenk commented on packages/oi4-oec-service-node/tests/fixtures/encrypted-client-cert.crt
> +-----BEGIN CERTIFICATE-----
Please move to src/__fixtures__

2022-06-01 12:54 UTC, Weinschenk commented on packages/oi4-oec-service-node/tests/fixtures/encrypted-client-key.key
> +-----BEGIN ENCRYPTED PRIVATE KEY-----
Please move to src/__fixtures__

2022-06-01 12:54 UTC, Weinschenk commented on packages/oi4-oec-service-node/tests/fixtures/passphrase.txt
> +abcd
Please move to src/__fixtures__

2022-06-02 06:38 UTC, Weinschenk approved these changes

2022-06-02 06:39 UTC, merged