OI4-205
OI4/oi4-oec-service pull request #42
Opened 2022-06-02 09:54 UTC by Weinschenk

2022-06-02 10:04 UTC, vdedominicis-EH requested changes
All good :) There's just the tiny change I marked as code change but beside this looks fine.

2022-06-02 10:04 UTC, vdedominicis-EH commented on packages/oi4-oec-service-opcua-model/src/index.ts
> +export const jsonSchemaBuilder = () => {
What about exporting this function into a separate helper or utils file? It has no dependency from the rest of the code and it is pretty big.

2022-06-03 09:31 UTC, Weinschenk commented on packages/oi4-oec-service-opcua-model/src/index.ts
> +export const jsonSchemaBuilder = () => {
Valid point. Refactored the builder to be part of the OpcUaSchemaProvider.ts and OecSchemaProvider.ts. Furthermore I removed the duplicate code.

Please give it another try...

2022-06-03 09:36 UTC, vdedominicis-EH approved these changes
looks good :)

2022-06-03 09:42 UTC, merged