OI4-294 Fixed failing tests
OI4/oi4-oec-service pull request #65
Opened 2022-06-23 04:19 UTC by Weinschenk

2022-06-23 08:42 UTC, vdedominicis-EH requested changes
All good. I also needed to fix the OI4Application.test.ts errors in order to add some test, therefore this file will create conflicts with my current branch. Anyway we can manage it while merging, no problem.

2022-06-23 08:42 UTC, vdedominicis-EH commented on packages/oi4-oec-service-node/tests/Utilities/Helpers/ClientCallbacksHelper.test.ts
> +        setLogger(loggerItems.fakeLogger);
I really like this setLogger, but I wonder if it is meaningful in the Logger.ts class the logger can be set multiple times. Maybe something like 
if(logger === undefined) { ... }
else { throw new Error('logger already existing' };

2022-06-24 06:49 UTC, Weinschenk commented on packages/oi4-oec-service-node/tests/Utilities/Helpers/ClientCallbacksHelper.test.ts
> +        setLogger(loggerItems.fakeLogger);
I twisted my head around this many time. The problem is with the Singleton. It makes sense to have, because creation of logger is a costly task. But it produces coupling and prevents dependency injection.
"Overwriting" the logger with multiple sets is fine I guess and needed, because it is already initialized in the beginning.

2022-06-24 07:52 UTC, vdedominicis-EH approved these changes
All good :)

2022-06-24 07:52 UTC, merged