OI4-55
OI4/oi4-oec-service pull request #68
Opened 2022-06-28 09:12 UTC by vdedominicis-EH

2022-06-28 09:33 UTC, Weinschenk requested changes

2022-06-28 09:33 UTC, Weinschenk commented on packages/oi4-oec-service-node/src/Utilities/Helpers/ClientPayloadHelper.ts
>          if (Number.isNaN(dataSetWriterIdFilter)) { // Try to filter with licenseId
Check for NaN is obsolete as it is always a number (it used to be string in the past)

2022-06-28 09:33 UTC, Weinschenk commented on packages/oi4-oec-service-node/src/Utilities/Helpers/ClientPayloadHelper.ts
> +    createLicenseSendResourcePayload(applicationResources: IOI4ApplicationResources, dataSetWriterIdFilter: number, resource: string, filter: string = undefined): ValidatedPayload {
According to the spec, we need to "filters" for the license; <oi4Identifier> and <licenseId>.
It is possible to only provide the oi4Identifier, but not the licenseId. Therefore I suggest the following method signature:
```suggestion
    createLicenseSendResourcePayload(applicationResources: IOI4ApplicationResources, oi4Identifier?: string, licenseId?: string = undefined): ValidatedPayload {
```

2022-06-28 09:33 UTC, Weinschenk commented on packages/oi4-oec-service-node/src/Utilities/Helpers/ClientPayloadHelper.ts
>          if (Number.isNaN(dataSetWriterIdFilter)) { // Try to filter with licenseId
Please rework the nested if statements.

2022-06-28 09:37 UTC, vdedominicis-EH commented on packages/oi4-oec-service-node/src/Utilities/Helpers/ClientPayloadHelper.ts
>          if (Number.isNaN(dataSetWriterIdFilter)) { // Try to filter with licenseId
Fixed

2022-06-28 10:49 UTC, vdedominicis-EH commented on packages/oi4-oec-service-node/src/Utilities/Helpers/ClientPayloadHelper.ts
> +    createLicenseSendResourcePayload(applicationResources: IOI4ApplicationResources, dataSetWriterIdFilter: number, resource: string, filter: string = undefined): ValidatedPayload {
discussed and fixed together

2022-06-28 10:50 UTC, vdedominicis-EH commented on packages/oi4-oec-service-node/src/Utilities/Helpers/ClientPayloadHelper.ts
>          if (Number.isNaN(dataSetWriterIdFilter)) { // Try to filter with licenseId
done implicitly while dealing with the above point

2022-06-29 06:23 UTC, Weinschenk approved these changes

2022-06-29 09:55 UTC, merged