V1.0 schema update
OI4/oi4-oec-service pull request #70
Opened 2022-06-29 09:24 UTC by chrfranz

Updated JSON schemas according OEC development guideline 1.0.0. Added some unit tests.

2022-06-29 11:25 UTC, Weinschenk requested changes
See comment on baseEvent

2022-06-29 11:25 UTC, Weinschenk commented on packages/oi4-oec-json-schemas/src/schemas/event.schema.json
> +    "statusEvent": {
Why not use a baseEvent with the common fields?

2022-06-29 15:04 UTC, chrfranz commented on packages/oi4-oec-json-schemas/src/schemas/event.schema.json
> +    "statusEvent": {
It seems not possible to use the `allOf`keyword together with `additionalProperties: false`. 
* If the `baseEvent` forbids additional properties then all new properties in the derived schema are also forbidden. This means that the properties `category` and `details` are treated as errors during schema validation.
* If the `baseEvent` does not forbid additional properties then a message can contain additional properties and still validates against the schema.

This problem is described here: https://stackoverflow.com/questions/58784142/jsonschema-extending-and-no-additional-properties

At the moment I have removed all usages of the `allOf` keyword so that `additionalProperties:false` works as expected and forbids every unknown property. This has the drawback of some duplicate code. If we decide to use the `Draft 2019-09` schemas then we can use the new feature `unevaluatedProperties:false`.

2022-06-30 06:12 UTC, Weinschenk approved these changes

2022-06-30 06:12 UTC, merged