Fixed loading of mam object
OI4/oi4-oec-service pull request #84
Opened 2022-07-06 15:39 UTC by chrfranz

The master asset model was loaded in a way that all methods (like `resourceType`) were missing. 
See https://stackoverflow.com/questions/22875636/how-do-i-cast-a-json-object-to-a-typescript-class

2022-07-08 07:22 UTC, Weinschenk requested changes

2022-07-08 07:22 UTC, Weinschenk commented on packages/oi4-oec-service-node/src/application/OI4ApplicationResources.ts
> +            const mam = new MasterAssetModel();
```suggestion
            return MasterAssetModel.clone(JSON.parse(readFileSync(path, 'utf8')));
```

There is already a clone function on the MasterAssetModel class, that is among others intended for JSON deserialization

2022-07-08 07:57 UTC, chrfranz commented on packages/oi4-oec-service-node/src/application/OI4ApplicationResources.ts
> +            const mam = new MasterAssetModel();
`clone` function is now used

2022-07-15 12:31 UTC, Weinschenk approved these changes

2022-07-15 12:31 UTC, merged